import type { BloomGoal } from "./types";

/** Placeholder goals — replaced by real data once goal tracking is wired up. */
export const seedGoals: BloomGoal[] = [
  {
    id: "lose-5kg",
    title: "Lose 5 kg",
    type: "outcome",
    why: "I want to feel lighter on long walks with the dog.",
    measure: { kind: "automatic", metric: "weight", unit: "kg", start: 73, target: 68 },
    current: 71.4,
    startDate: "2026-05-04",
    targetDate: "2026-09-15",
    status: "on-track",
    accent: "sage",
    notes: "Weighing in on Monday mornings before breakfast keeps the trend honest.",
    updates: [
      { id: "u1", date: "24 Jul", title: "Weighed in at 71.4 kg", detail: "Down 0.3 kg on last week." },
      { id: "u2", date: "17 Jul", title: "Weighed in at 71.7 kg" },
      { id: "u3", date: "04 May", title: "Goal created", detail: "Starting from 73.0 kg." },
    ],
  },
  {
    id: "protein-140",
    title: "140 g protein a day",
    type: "habit",
    why: "Recovery between sessions has been slow.",
    measure: { kind: "automatic", metric: "protein", unit: "g", start: 95, target: 140 },
    current: 128,
    startDate: "2026-06-01",
    targetDate: "2026-08-31",
    status: "behind",
    accent: "lavender",
    notes: "A yoghurt in the afternoon usually closes the gap.",
    updates: [
      { id: "u1", date: "24 Jul", title: "7-day average 128 g", detail: "Up 6 g on the previous week." },
      { id: "u2", date: "01 Jun", title: "Goal created" },
    ],
  },
  {
    id: "train-4x",
    title: "Train four times a week",
    type: "habit",
    measure: { kind: "count", metric: "training", unit: "sessions", start: 1, target: 4 },
    current: 3,
    startDate: "2026-06-15",
    targetDate: "2026-10-01",
    status: "ahead",
    accent: "lavender",
    updates: [
      { id: "u1", date: "23 Jul", title: "Third session logged", detail: "Easy 40 minute run." },
      { id: "u2", date: "15 Jun", title: "Goal created" },
    ],
  },
  {
    id: "calmer-evenings",
    title: "Calmer evenings",
    type: "wellbeing",
    why: "Evenings have felt rushed and I want them back.",
    measure: { kind: "self-assessment", metric: "mood", start: 5, target: 8 },
    current: 7.4,
    startDate: "2026-07-01",
    targetDate: "2026-09-30",
    status: "on-track",
    accent: "blush",
    notes: "Screens off by 21:30 makes the biggest difference.",
    updates: [
      { id: "u1", date: "22 Jul", title: "Rated the week 7.4", detail: "Three calm evenings in a row." },
      { id: "u2", date: "01 Jul", title: "Goal created" },
    ],
  },
  {
    id: "lisbon-trip",
    title: "Book a long weekend in Lisbon",
    type: "life-event",
    why: "We keep talking about it and never doing it.",
    measure: { kind: "date", targetOn: "2026-10-09" },
    startDate: "2026-07-10",
    status: "on-track",
    accent: "sky",
    notes: "Flights are cheapest midweek.",
    updates: [{ id: "u1", date: "10 Jul", title: "Goal created" }],
  },
  {
    id: "read-12",
    title: "Read twelve books this year",
    type: "outcome",
    measure: { kind: "count", unit: "books", start: 0, target: 12 },
    current: 5,
    startDate: "2026-01-02",
    targetDate: "2026-12-31",
    status: "behind",
    accent: "stone",
    updates: [{ id: "u1", date: "02 Jan", title: "Goal created" }],
  },
  {
    id: "water-2l",
    title: "Two litres of water daily",
    type: "habit",
    measure: { kind: "automatic", metric: "water", unit: "L", start: 1, target: 2 },
    current: 2,
    startDate: "2026-04-02",
    targetDate: "2026-07-20",
    status: "ahead",
    accent: "sky",
    completedAt: "2026-07-18",
    updates: [
      { id: "u1", date: "18 Jul", title: "Goal complete", detail: "Thirty days at or above target." },
      { id: "u2", date: "02 Apr", title: "Goal created" },
    ],
  },
];
