import type { BloomGoal } from "./types";

/** Placeholder goals — replaced by real data once goal tracking is wired up. */
export const seedGoals: BloomGoal[] = [
  {
    id: "lose-5kg",
    title: "Lose 5 kg",
    type: "outcome",
    metric: "weight",
    why: "I want to feel lighter on long walks with the dog.",
    current: 71.4,
    start: 73,
    target: 68,
    unit: "kg",
    startDate: "2026-05-04",
    targetDate: "2026-09-15",
    status: "on-track",
    accent: "sage",
    notes: "Weighing in on Monday mornings before breakfast keeps the trend honest.",
    updates: [
      { id: "u1", date: "24 Jul", title: "Weighed in at 71.4 kg", detail: "Down 0.3 kg on last week." },
      { id: "u2", date: "17 Jul", title: "Weighed in at 71.7 kg" },
      { id: "u3", date: "04 May", title: "Goal created", detail: "Starting from 73.0 kg." },
    ],
  },
  {
    id: "protein-140",
    title: "140 g protein a day",
    type: "habit",
    metric: "protein",
    why: "Recovery between sessions has been slow.",
    current: 128,
    start: 95,
    target: 140,
    unit: "g",
    startDate: "2026-06-01",
    targetDate: "2026-08-31",
    status: "behind",
    accent: "blush",
    notes: "A yoghurt in the afternoon usually closes the gap.",
    updates: [
      { id: "u1", date: "24 Jul", title: "7-day average 128 g", detail: "Up 6 g on the previous week." },
      { id: "u2", date: "01 Jun", title: "Goal created" },
    ],
  },
  {
    id: "train-4x",
    title: "Train four times a week",
    type: "habit",
    metric: "training",
    current: 3,
    start: 1,
    target: 4,
    unit: "sessions",
    startDate: "2026-06-15",
    targetDate: "2026-10-01",
    status: "ahead",
    accent: "lavender",
    updates: [
      { id: "u1", date: "23 Jul", title: "Third session logged", detail: "Easy 40 minute run." },
      { id: "u2", date: "15 Jun", title: "Goal created" },
    ],
  },
  {
    id: "calmer-evenings",
    title: "Calmer evenings",
    type: "wellbeing",
    metric: "mood",
    why: "Evenings have felt rushed and I want them back.",
    current: 7.4,
    start: 5,
    target: 8,
    unit: "/10",
    startDate: "2026-07-01",
    targetDate: "2026-09-30",
    status: "on-track",
    accent: "sky",
    notes: "Screens off by 21:30 makes the biggest difference.",
    updates: [
      { id: "u1", date: "22 Jul", title: "Mood average 7.4", detail: "Three calm evenings in a row." },
      { id: "u2", date: "01 Jul", title: "Goal created" },
    ],
  },
  {
    id: "water-2l",
    title: "Two litres of water daily",
    type: "habit",
    metric: "water",
    current: 2,
    start: 1,
    target: 2,
    unit: "L",
    startDate: "2026-04-02",
    targetDate: "2026-07-20",
    status: "ahead",
    accent: "sky",
    completedAt: "2026-07-18",
    updates: [
      { id: "u1", date: "18 Jul", title: "Goal complete", detail: "Thirty days at or above target." },
      { id: "u2", date: "02 Apr", title: "Goal created" },
    ],
  },
];
